version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: tea-shop-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: teashop
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: tea_shop
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
